### ISSUE TITLE
Cannot find module 'hap-nodejs' on homebridge-pc-volume v1.2.0 (2020-04-26)

### ISSUE THREAD

**Issue by SKnight79** [JosephDuffy/homebridge-pc-volume#440]
[4/28/2020, 5:39:26 PM] ====================                                                                                           
[4/28/2020, 5:39:26 PM] ERROR LOADING PLUGIN homebridge-pc-volume:                                                                     
[4/28/2020, 5:39:26 PM] Error: Cannot find module 'hap-nodejs'                                                                         
Require stack:                                                                                                                         
- /usr/local/lib/node_modules/homebridge-pc-volume/build/ServiceWrapper.js                                                             
- /usr/local/lib/node_modules/homebridge-pc-volume/build/ComputerSpeakersAccessory.js                                                  
- /usr/local/lib/node_modules/homebridge-pc-volume/build/index.js                                                                      
- /usr/local/lib/node_modules/homebridge/lib/plugin.js                                                                                 
- /usr/local/lib/node_modules/homebridge/lib/server.js                                                                                 
- /usr/local/lib/node_modules/homebridge/lib/cli.js                                                                                    
- /usr/local/lib/node_modules/homebridge/bin/homebridge                                                                                
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)                                                            at Function.Module._load (internal/modules/cjs/loader.js:835:27)                                                                   
    at Module.require (internal/modules/cjs/loader.js:1012:19)                                                                         
    at require (internal/modules/cjs/helpers.js:72:18)                                                                                 
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-pc-volume/build/ServiceWrapper.js:3:22)                              
    at Module._compile (internal/modules/cjs/loader.js:1123:30)                                                                        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)                                                          
    at Module.load (internal/modules/cjs/loader.js:972:32)                                                                                 at Function.Module._load (internal/modules/cjs/loader.js:872:14)                                                                   
    at Module.require (internal/modules/cjs/loader.js:1012:19)                                                                         
    at require (internal/modules/cjs/helpers.js:72:18)                                                                                 
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-pc-volume/build/ComputerSpeakersAccessory.js:17:42)                  
    at Module._compile (internal/modules/cjs/loader.js:1123:30)                                                                        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)                                                          
    at Module.load (internal/modules/cjs/loader.js:972:32)                                                                             
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
[4/28/2020, 5:39:26 PM] ====================

I have two computers, both running home bridge. I use one to test updates and the other one is for production.

The version homebridge-pc-volume v1.1.0 seems to work fine. If I upgrade to this version homebridge-pc-volume v1.2.0 (2020-04-26), the error appears, the service craps out and goes into a restart cycle.

Is there any way to install homebridge-pc-volume v1.1.0 to correct until the issue is resolved?

**Comment by SKnight79** [comment]
I was able to uninstall 1.2.0 and install 1.1.0. No issues this far.

**Comment by JosephDuffy** [comment]
Thank you for raising this (and so quickly after the release).

I've got a PR open that should fix this. I'll comment again when the fix is released (1.2.1).

**Comment by SKnight79** [comment]
Ok to try upgrade again?

**Comment by JosephDuffy** [comment]
> Ok to try upgrade again?

1.2.1 was just released. The (new) end-to-end tests are passing and it's working locally so let me know how you get on

**Comment by SKnight79** [comment]
Yep it’s working. Thank you. In testing I noticed on the desktop it’s fine. On the laptop it controls the internal speaker audio device. I happen to have the laptop plugged into a docking station with its own audio device port which is a separate audio device. I have it selected. 

As a future enhancement pick the defaulted audio device or have an option to configure which one to control?

**Comment by JosephDuffy** [comment]
I see how this could be a useful addition. Maybe even the option to switch the current output.

This project uses https://github.com/LinusU/node-loudness, which only supports changing the volume/(un)muting. I don't have the time to build something that would change the output device. If you know of an existing project that could be used I'll look in to integrating it.
