### ISSUE TITLE
Support for Windows？

### ISSUE THREAD

**Issue by Lon1st** [JosephDuffy/homebridge-pc-volume#8]
I noticed node-loudness had already supported Windows. Is there anything i can do to make this plugin work with Windows?

**Comment by JosephDuffy** [comment]
I've not tested it on Windows, but it does looks like node-loudness has had support for Windows for over a year!

Nothing about homebridge-pc-volume restricts to macOS/linux, so it could just work. I've recently added CI, which does run on Windows and passes, so I know it all installs correctly. However, this does not test changing the volume.

Are you able to try this on Windows and report if it works or not?

**Comment by Lon1st** [comment]
I clone the project and use "npm install -g ./" to install it locally. But homebridge keeps showing this error

`ERROR LOADING PLUGIN homebridge-pc-volume:
[2018-12-13 10:45:45] Error: Cannot find module 'C:\Users\Lang\AppData\Roaming\npm\node_modules\homebridge-pc-volume\build\index.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Plugin.load (C:\Users\Lang\AppData\Roaming\npm\node_modules\homebridge\lib\plugin.js:72:23)
    at Server.<anonymous> (C:\Users\Lang\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:149:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (C:\Users\Lang\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:141:22)
    at new Server (C:\Users\Lang\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:57:24)
    at module.exports (C:\Users\Lang\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:30:16)`

**Comment by JosephDuffy** [comment]
The project is working in Windows on CI. If that doesn't work please re-open this issue, or create a new one!
